# Generated by Django 3.2.16 on 2023-06-06 09:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'is_published',
                    models.BooleanField(
                        default=True, verbose_name='опубликовано'
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True, verbose_name='дата публикации'
                    ),
                ),
                (
                    'title',
                    models.CharField(max_length=256, verbose_name='категория'),
                ),
                ('slug', models.SlugField(unique=True, verbose_name='слаг')),
                ('description', models.TextField(verbose_name='описание')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'is_published',
                    models.BooleanField(
                        default=True, verbose_name='опубликовано'
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True, verbose_name='дата публикации'
                    ),
                ),
                ('name', models.CharField(max_length=256)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'is_published',
                    models.BooleanField(
                        default=True, verbose_name='опубликовано'
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True, verbose_name='дата публикации'
                    ),
                ),
                (
                    'title',
                    models.CharField(
                        max_length=256, verbose_name='заголовок поста'
                    ),
                ),
                ('text', models.TextField(verbose_name='текст поста')),
                (
                    'pub_date',
                    models.DateTimeField(verbose_name='дата публикации'),
                ),
                (
                    'author',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='post',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'category',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='post',
                        to='blog.category',
                    ),
                ),
                (
                    'location',
                    models.ForeignKey(
                        default='Планета Земля',
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='post',
                        to='blog.location',
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
