# Generated by Django 3.2.16 on 2023-06-06 10:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('blog', '0002_auto_20230606_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(
                auto_now_add=True, verbose_name='дата публикации'
            ),
        ),
        migrations.AlterField(
            model_name='category',
            name='is_published',
            field=models.BooleanField(
                default=True,
                help_text='Снимите галочку, чтобы скрыть публикацию.',
                verbose_name='опубликовано',
            ),
        ),
        migrations.AlterField(
            model_name='location',
            name='created_at',
            field=models.DateTimeField(
                auto_now_add=True, verbose_name='дата публикации'
            ),
        ),
        migrations.AlterField(
            model_name='location',
            name='is_published',
            field=models.BooleanField(
                default=True,
                help_text='Снимите галочку, чтобы скрыть публикацию.',
                verbose_name='опубликовано',
            ),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(
                auto_now_add=True, verbose_name='дата публикации'
            ),
        ),
        migrations.AlterField(
            model_name='post',
            name='is_published',
            field=models.BooleanField(
                default=True,
                help_text='Снимите галочку, чтобы скрыть публикацию.',
                verbose_name='опубликовано',
            ),
        ),
    ]
