# Generated by Django 3.2.16 on 2023-06-07 12:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('blog', '0003_auto_20230606_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(
                auto_now_add=True, verbose_name='Добавлено'
            ),
        ),
        migrations.AlterField(
            model_name='category',
            name='is_published',
            field=models.BooleanField(
                default=True,
                help_text='Снимите галочку, чтобы скрыть публикацию.',
                verbose_name='Опубликовано',
            ),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=256, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='location',
            name='created_at',
            field=models.DateTimeField(
                auto_now_add=True, verbose_name='Добавлено'
            ),
        ),
        migrations.AlterField(
            model_name='location',
            name='is_published',
            field=models.BooleanField(
                default=True,
                help_text='Снимите галочку, чтобы скрыть публикацию.',
                verbose_name='Опубликовано',
            ),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(
                auto_now_add=True, verbose_name='Добавлено'
            ),
        ),
        migrations.AlterField(
            model_name='post',
            name='is_published',
            field=models.BooleanField(
                default=True,
                help_text='Снимите галочку, чтобы скрыть публикацию.',
                verbose_name='Опубликовано',
            ),
        ),
    ]
