# Generated by Django 3.2.16 on 2023-06-07 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('blog', '0004_auto_20230607_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(
                default='Планета Земля',
                max_length=256,
                verbose_name='Название места',
            ),
        ),
        migrations.AlterField(
            model_name='post',
            name='location',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='post',
                to='blog.location',
                verbose_name='Местоположение',
            ),
        ),
    ]
